root: true
extends:
  - universe/native
  - universe/web
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - airbnb
  - airbnb-typescript
  - prettier
parserOptions:
  project: './tsconfig.json'
rules:
  max-len: ['error', { 'code': 140 }]
  react/prop-types: off
