projects:
  emojoeexpo:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/types/api.ts
        docsFilePath: src/graphql
        maxDepth: 3
extensions:
  amplify:
    version: 3
