/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'eu-central-1',
  aws_cognito_identity_pool_id:
    'eu-central-1:d4a95800-8f7e-473b-a374-22d8e7e900a7',
  aws_cognito_region: 'eu-central-1',
  aws_user_pools_id: 'eu-central-1_d4XLP47UB',
  aws_user_pools_web_client_id: 'blntfj9bg4c1l9vora84nrsb',
  oauth: {
    domain:
      'emojoeexpo5f85b84d-5f85b84d-dev.auth.eu-central-1.amazoncognito.com',
    scope: [
      'phone',
      'email',
      'openid',
      'profile',
      'aws.cognito.signin.user.admin',
    ],
    redirectSignIn:
      'emojoe2://,exp://127.0.0.1:19000/--/,https://emojoe-expo.vercel.app',
    redirectSignOut:
      'emojoe2://,exp://127.0.0.1:19000/--/,https://emojoe-expo.vercel.app',
    responseType: 'code',
  },
  federationTarget: 'COGNITO_USER_POOLS',
  aws_cognito_username_attributes: [],
  aws_cognito_social_providers: ['GOOGLE'],
  aws_cognito_signup_attributes: ['EMAIL'],
  aws_cognito_mfa_configuration: 'OFF',
  aws_cognito_mfa_types: ['SMS'],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ['EMAIL'],
  aws_appsync_graphqlEndpoint:
    'https://t5thtg775zbqvarjktx3od3cam.appsync-api.eu-central-1.amazonaws.com/graphql',
  aws_appsync_region: 'eu-central-1',
  aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
};

export default awsmobile;
